server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE
  datasource:
    url: jdbc:mysql://taskservice.cz44i6aqk7tg.eu-north-1.rds.amazonaws.com:3306/taskService
    username: admin
    password: $7090Ashok
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/