
#spring.application.name=SUBMISSION-SERVICE

server:
  port: 5003    
    

eureka:
 instance:
   prefer-ip-address: true
 client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


spring:
  application:
    name: SUBMISSION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/task_submission_service
    username: root
    password: kartik@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  